name: kd_messenger
description: Standalone KD Messenger client
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0

flutter:
  uses-material-design: true
