(()=>{
  if(window.__KD_CALLS__)return;
  const wait=(n=0)=>{const c=window.__KD_SUPABASE_CLIENT__;if(!c){if(n<40)setTimeout(()=>wait(n+1),250);return}init(c)};
  const init=client=>{
    window.__KD_CALLS__=true;
    const state={pc:null,channel:null,callId:null,peerId:null,conversationId:null,local:null,remote:null,muted:false,cameraOff:false,screen:null,role:null};
    const rtc={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]};
    const css=`#kd-call{position:fixed;inset:0;z-index:99990;display:none;background:rgba(7,7,11,.96);backdrop-filter:blur(22px);color:#fff;font:600 14px system-ui,sans-serif}#kd-call.show{display:block}#kd-call .remote{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;background:#111}#kd-call .local{position:absolute;right:18px;top:18px;width:min(30vw,260px);aspect-ratio:16/10;object-fit:cover;border-radius:16px;background:#222;box-shadow:0 10px 40px #0008;z-index:2}#kd-call .bar{position:absolute;left:50%;bottom:28px;transform:translateX(-50%);display:flex;gap:10px;align-items:center;padding:10px;border-radius:22px;background:#17171fdd;border:1px solid #ffffff18;z-index:3}#kd-call button{border:0;border-radius:16px;width:48px;height:48px;background:#292934;color:#fff;font-size:19px;cursor:pointer}#kd-call button.end{background:#e5484d}#kd-call .incoming{position:absolute;inset:0;display:grid;place-items:center;text-align:center;z-index:4;background:#0b0b10e8}#kd-call .incoming .box{padding:28px}.kd-call-actions{display:flex;gap:8px;align-items:center}.kd-call-button{border:0;background:transparent;color:inherit;cursor:pointer;font-size:18px;padding:7px}`;
    const style=document.createElement('style');style.id='kd-calls-css';style.textContent=css;document.head.appendChild(style);
    const root=document.createElement('div');root.id='kd-call';root.innerHTML='<video class="remote" autoplay playsinline></video><video class="local" autoplay muted playsinline></video><div class="bar"><button data-act="mute" title="Микрофон">🎙</button><button data-act="camera" title="Камера">📹</button><button data-act="screen" title="Экран">🖥</button><button data-act="end" class="end" title="Завершить">☎</button></div><div class="incoming" hidden><div class="box"><h2 class="incoming-title">Входящий звонок</h2><p class="incoming-type"></p><div class="kd-call-actions"><button data-act="accept">Принять</button><button data-act="reject" class="end">Отклонить</button></div></div></div>';document.body.appendChild(root);
    const remote=root.querySelector('.remote'),local=root.querySelector('.local'),incoming=root.querySelector('.incoming');
    const session=async()=>((await client.auth.getSession()).data||{}).session||null;
    const emit=async(type,payload)=>{if(!state.channel)return;await state.channel.send({type:'broadcast',event:'call',payload:{type,...payload,callId:state.callId,from:(await session())?.user?.id}})};
    const closeMedia=()=>{[state.local,state.screen].forEach(s=>s?.getTracks?.().forEach(t=>t.stop()));state.local=null;state.screen=null;remote.srcObject=null;local.srcObject=null};
    const teardown=async(notify=true)=>{if(notify)await emit('end',{}).catch(()=>{});try{state.pc?.close()}catch{};state.pc=null;state.callId=null;state.peerId=null;state.role=null;state.muted=false;state.cameraOff=false;incoming.hidden=true;root.classList.remove('show');closeMedia();if(state.channel){try{await client.removeChannel(state.channel)}catch{};state.channel=null}};
    const attach=(pc)=>{pc.ontrack=e=>{remote.srcObject=e.streams[0]||new MediaStream([e.track])};pc.onicecandidate=e=>{if(e.candidate)emit('ice',{candidate:e.candidate})};pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc.connectionState)&&state.pc===pc)teardown(false)}};
    const makePC=()=>{const pc=new RTCPeerConnection(rtc);attach(pc);return pc};
    const subscribe=async(conv,callId)=>{state.conversationId=conv;state.callId=callId;state.channel=client.channel('kd-call-'+conv,{config:{private:true}});state.channel.on('broadcast',{event:'call'},async({payload})=>{if(!payload||payload.callId!==state.callId)return;const me=(await session())?.user?.id;if(payload.from===me)return;switch(payload.type){case'offer':await onOffer(payload);break;case'answer':await state.pc?.setRemoteDescription(payload.sdp);break;case'ice':if(payload.candidate)await state.pc?.addIceCandidate(payload.candidate).catch(()=>{});break;case'end':case'reject':await teardown(false);break;case'accept':if(state.role==='caller')await makeOffer();break}});await state.channel.subscribe();};
    const getMedia=async(video)=>{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Камера/микрофон недоступны в этом браузере');return navigator.mediaDevices.getUserMedia({audio:true,video:!!video})};
    const start=async({conversationId,peerId,video=true})=>{const s=await session();if(!s)throw new Error('Необходима авторизация');if(!conversationId||!peerId)throw new Error('Не указан собеседник');await teardown(false);state.peerId=peerId;state.role='caller';state.callId=crypto.randomUUID();await subscribe(conversationId,state.callId);state.local=await getMedia(video);local.srcObject=state.local;state.pc=makePC();state.local.getTracks().forEach(t=>state.pc.addTrack(t,state.local));root.classList.add('show');await emit('ring',{peerId,type:video?'video':'audio'});await makeOffer()};
    const makeOffer=async()=>{if(!state.pc)return;const offer=await state.pc.createOffer();await state.pc.setLocalDescription(offer);await emit('offer',{sdp:state.pc.localDescription})};
    const onOffer=async payload=>{if(state.role==='caller')return;if(!state.pc)state.pc=makePC();if(!state.local){try{state.local=await getMedia(payload.type==='video');local.srcObject=state.local;state.local.getTracks().forEach(t=>state.pc.addTrack(t,state.local))}catch(e){await emit('reject',{reason:e.message});return}}await state.pc.setRemoteDescription(payload.sdp);const answer=await state.pc.createAnswer();await state.pc.setLocalDescription(answer);await emit('answer',{sdp:state.pc.localDescription})};
    const incomingRing=async payload=>{if(state.callId)return;state.callId=payload.callId;state.peerId=payload.from;state.role='callee';incoming.querySelector('.incoming-type').textContent=payload.type==='video'?'Видеозвонок':'Аудиозвонок';incoming.hidden=false;root.classList.add('show');state.conversationId=state.conversationId||payload.conversationId};
    root.addEventListener('click',async e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(!a)return;try{if(a==='end'||a==='reject'){await teardown(true);return}if(a==='accept'){incoming.hidden=true;if(!state.channel){await subscribe(state.conversationId,state.callId)}await emit('accept',{});root.classList.add('show');return}if(!state.pc)return;if(a==='mute'){state.muted=!state.muted;state.local?.getAudioTracks().forEach(t=>t.enabled=!state.muted);e.target.textContent=state.muted?'🔇':'🎙'}if(a==='camera'){state.cameraOff=!state.cameraOff;state.local?.getVideoTracks().forEach(t=>t.enabled=!state.cameraOff);e.target.textContent=state.cameraOff?'🚫':'📹'}if(a==='screen'){if(!navigator.mediaDevices.getDisplayMedia)throw new Error('Демонстрация экрана не поддерживается');if(!state.screen){state.screen=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const track=state.screen.getVideoTracks()[0];const sender=state.pc.getSenders().find(x=>x.track?.kind==='video');if(sender)await sender.replaceTrack(track);track.onended=()=>{const cam=state.local?.getVideoTracks()[0];if(sender&&cam)sender.replaceTrack(cam);state.screen=null}}}}catch(err){console.error('KD call',err)}});
    window.KDCalls={startAudio:(conversationId,peerId)=>start({conversationId,peerId,video:false}),startVideo:(conversationId,peerId)=>start({conversationId,peerId,video:true}),end:()=>teardown(true)};
    window.KDCallUI={open:window.KDCalls.startVideo};
  };
  wait();
})();