(()=>{
'use strict';
const sb=window.supabase?.createClient('https://qqofizfqkctycyeafgsa.supabase.co','sb_publishable_MTZuMyuzb0XdtBy3ZGIQZw_pHbXc9xK');
if(!sb)return;
const css=document.createElement('style');css.textContent=`.info-panel .profile-cover{position:relative}.info-panel .profile-avatar{overflow:hidden;cursor:pointer}.info-panel .profile-avatar img{width:100%;height:100%;object-fit:cover;display:block}.info-panel .profile-info{cursor:pointer}.kd-info-status{display:inline-flex;align-items:center;gap:6px;margin-top:5px;font-size:12px;color:#8f96a8}.kd-info-status-dot{width:7px;height:7px;border-radius:50%;background:#687080}.kd-info-status-dot.online{background:#35d07f;box-shadow:0 0 7px #35d07f88}.info-panel .info-block[data-kd-bio] p{white-space:pre-wrap;overflow-wrap:anywhere}.info-panel .info-block[data-kd-bio].empty{display:none}`;document.head.appendChild(css);
let cid=null,uid=null,profile=null,busy=false,last=0;
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const initials=p=>(String(p?.display_name||p?.username||'KD').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'KD');
function statusText(p){if(p.is_online)return 'В сети';if(!p.last_seen)return 'Не в сети';return 'был(а) '+new Date(p.last_seen).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
async function currentUser(){return (await sb.auth.getSession()).data.session?.user?.id}
async function load(){if(busy)return;const active=window.kdActiveConversation;if(!active)return;const now=Date.now();if(active===cid&&now-last<3000)return;busy=true;try{const me=await currentUser();if(!me)return;const m=await sb.from('kd_conversation_members').select('user_id').eq('conversation_id',active);const other=(m.data||[]).find(x=>x.user_id!==me);if(!other?.user_id)return;const r=await sb.from('kd_profiles').select('id,display_name,username,bio,avatar_url,status,is_online,last_seen').eq('id',other.user_id).maybeSingle();if(r.error||!r.data)return;cid=active;uid=other.user_id;profile=r.data;last=now;render(profile)}finally{busy=false}}
function openProfile(){if(profile?.username)location.href=location.pathname+'?user='+encodeURIComponent(profile.username)}
function render(p){const panel=document.querySelector('.info-panel');if(!panel)return;const avatar=panel.querySelector('.profile-avatar');if(avatar){avatar.innerHTML=p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="${esc(p.display_name||'Аватар')}">`:`<span>${esc(initials(p))}</span>`;avatar.onclick=openProfile;avatar.title='Открыть профиль'}const name=panel.querySelector('#infoName'),handle=panel.querySelector('#infoHandle'),bio=panel.querySelector('.profile-info p');if(name){name.textContent=p.display_name||p.username||'Пользователь'}if(handle)handle.textContent=p.username?`@${p.username}`:'';if(bio)bio.textContent=p.bio||'Нет описания';const pi=panel.querySelector('.profile-info');let st=pi?.querySelector('.kd-info-status');if(pi&&!st){st=document.createElement('div');st.className='kd-info-status';pi.appendChild(st)}if(st){st.innerHTML=`<i class="kd-info-status-dot ${p.is_online?'online':''}"></i><span>${esc(p.status||statusText(p))}</span>`}if(pi)pi.onclick=openProfile;let block=panel.querySelector('[data-kd-bio]');if(!block){block=panel.querySelector('.info-block');if(block)block.dataset.kdBio='1'}if(block){block.dataset.kdBio='1';block.classList.toggle('empty',!p.bio);const para=block.querySelector('p');if(para)para.textContent=p.bio||''}}
function boot(){load();setInterval(load,1500);window.addEventListener('hashchange',load)}
window.kdInfoSync=load;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
