(()=>{
'use strict';
const sb=window.supabase?.createClient('https://qqofizfqkctycyeafgsa.supabase.co','sb_publishable_MTZuMyuzb0XdtBy3ZGIQZw_pHbXc9xK');
if(!sb)return;
const css=document.createElement('style');css.textContent=`
.info-panel .profile-cover{position:relative}.info-panel .profile-avatar{overflow:hidden;cursor:pointer}.info-panel .profile-avatar img{width:100%;height:100%;object-fit:cover;display:block}.info-panel .profile-info{cursor:pointer}.kd-info-status{display:inline-flex;align-items:center;gap:6px;margin-top:5px;font-size:12px;color:#8f96a8}.kd-info-status-dot{width:7px;height:7px;border-radius:50%;background:#687080}.kd-info-status-dot.online{background:#35d07f;box-shadow:0 0 7px #35d07f88}.info-panel .info-block[data-kd-bio] p{white-space:pre-wrap;overflow-wrap:anywhere}.info-panel .info-block[data-kd-bio].empty{display:none}.info-panel .info-actions button{cursor:pointer}.kd-info-more{display:grid;gap:8px}.kd-info-more button{padding:12px;border:1px solid #303442;border-radius:12px;background:#151720;color:#fff;text-align:left;cursor:pointer}.kd-info-more button:hover{border-color:#7865ff}
`;document.head.appendChild(css);
let cid=null,uid=null,profile=null,busy=false,last=0,actionsBound=false;
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const initials=p=>(String(p?.display_name||p?.username||'KD').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'KD');
function statusText(p){if(p.is_online)return 'В сети';if(!p.last_seen)return 'Не в сети';return 'был(а) '+new Date(p.last_seen).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
async function currentUser(){return (await sb.auth.getSession()).data.session?.user?.id}
async function load(){if(busy)return;const active=window.kdActiveConversation;if(!active)return;const now=Date.now();if(active===cid&&now-last<3000)return;busy=true;try{const me=await currentUser();if(!me)return;const m=await sb.from('kd_conversation_members').select('user_id').eq('conversation_id',active);const other=(m.data||[]).find(x=>x.user_id!==me);if(!other?.user_id)return;const r=await sb.from('kd_profiles').select('id,display_name,username,bio,avatar_url,status,is_online,last_seen').eq('id',other.user_id).maybeSingle();if(r.error||!r.data)return;cid=active;uid=other.user_id;profile=r.data;last=now;render(profile)}finally{busy=false}}
function openProfile(){if(profile?.username)location.href=location.pathname+'?user='+encodeURIComponent(profile.username)}
function toast(text){const t=document.querySelector('#toast');if(t){t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}}
function quickMore(){
 const old=document.querySelector('.kd-info-more-modal');if(old)old.remove();
 if(!window.kdActiveConversation){toast('Сначала открой чат');return}
 const m=document.createElement('div');m.className='kd-modal kd-info-more-modal';m.innerHTML='<div class="kd-modal-card"><button class="kd-close">×</button><h2>Ещё</h2><div class="kd-info-more"><button data-a="profile">👤 Открыть профиль</button><button data-a="media">📁 Медиа и файлы</button><button data-a="unread">🔵 Отметить непрочитанным</button></div></div>';document.body.appendChild(m);
 m.querySelector('.kd-close').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};
 m.querySelector('[data-a="profile"]').onclick=()=>{m.remove();openProfile()};
 m.querySelector('[data-a="media"]').onclick=()=>{m.remove();window.kdOpenMediaPanel?window.kdOpenMediaPanel():toast('Медиа-панель ещё загружается')};
 m.querySelector('[data-a="unread"]').onclick=()=>{m.remove();window.kdMarkUnread?window.kdMarkUnread():toast('Функция ещё загружается')};
}
function bindActions(){if(actionsBound)return;const panel=document.querySelector('.info-panel');if(!panel)return;const bs=panel.querySelectorAll('.info-actions button');if(bs.length<3)return;actionsBound=true;bs[0].title='Настроить уведомления';bs[1].title='Поиск по сообщениям';bs[2].title='Дополнительные действия';bs[0].onclick=()=>{if(window.kdNotificationMode)window.kdNotificationMode();else toast('Настройки уведомлений ещё загружаются')};bs[1].onclick=()=>{if(window.kdSearchChat)window.kdSearchChat();else if(window.kdOpenMessageSearch)window.kdOpenMessageSearch();else toast('Поиск ещё загружается')};bs[2].onclick=quickMore}
function render(p){const panel=document.querySelector('.info-panel');if(!panel)return;const avatar=panel.querySelector('.profile-avatar');if(avatar){avatar.innerHTML=p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="${esc(p.display_name||'Аватар')}">`:`<span>${esc(initials(p))}</span>`;avatar.onclick=openProfile;avatar.title='Открыть профиль'}const name=panel.querySelector('#infoName'),handle=panel.querySelector('#infoHandle'),bio=panel.querySelector('.profile-info p');if(name)name.textContent=p.display_name||p.username||'Пользователь';if(handle)handle.textContent=p.username?`@${p.username}`:'';if(bio)bio.textContent=p.bio||'Нет описания';const pi=panel.querySelector('.profile-info');let st=pi?.querySelector('.kd-info-status');if(pi&&!st){st=document.createElement('div');st.className='kd-info-status';pi.appendChild(st)}if(st)st.innerHTML=`<i class="kd-info-status-dot ${p.is_online?'online':''}"></i><span>${esc(p.status||statusText(p))}</span>`;if(pi)pi.onclick=openProfile;let block=panel.querySelector('[data-kd-bio]');if(!block){block=panel.querySelector('.info-block');if(block)block.dataset.kdBio='1'}if(block){block.dataset.kdBio='1';block.classList.toggle('empty',!p.bio);const para=block.querySelector('p');if(para)para.textContent=p.bio||''}}
function boot(){load();bindActions();setInterval(()=>{load();bindActions()},1500);window.addEventListener('hashchange',load)}
window.kdInfoSync=load;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();