/* KD Messenger E2EE epoch storage bridge. Uses kd_conversation_key_epochs for v1..vN. */
(function(){'use strict';
const SB_URL='https://qqofizfqkctycyeafgsa.supabase.co',SB_KEY='sb_publishable_MTZuMyuzb0XdtBy3GZIQZw_pHbXc9xK';
let sb=null;const te=new TextEncoder(),td=new TextDecoder();
const b64=u=>btoa(String.fromCharCode(...new Uint8Array(u))),ub=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const stable=o=>JSON.stringify(o,Object.keys(o).sort());
function getSb(){if(sb)return sb;if(!window.supabase?.createClient)throw Error('Supabase unavailable');return sb=window.supabase.createClient(SB_URL,SB_KEY)}
async function me(){return (await getSb().auth.getSession()).data.session?.user?.id||null}
async function pub(j){return crypto.subtle.importKey('jwk',j,{name:'ECDH',namedCurve:'P-256'},false,[])}
async function wrap(key,p){const id=window.kdE2EE.getIdentity(),raw=await crypto.subtle.exportKey('raw',key),wk=await crypto.subtle.importKey('raw',await crypto.subtle.deriveBits({name:'ECDH',public:await pub(p)},id.ecdhPrivate,256),{name:'AES-GCM'},false,['encrypt','decrypt']),nonce=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:te.encode('KD-E2EE-WRAP-v1')},wk,raw);return{wrapped_key:b64(ct),wrap_nonce:b64(nonce)}}
async function sign(row){const id=window.kdE2EE.getIdentity(),d=stable({conversation_id:row.conversation_id,user_id:row.user_id,sender_user_id:row.sender_user_id,key_version:row.key_version,wrapped_key:row.wrapped_key,wrap_nonce:row.wrap_nonce,sender_public_key_jwk:row.sender_public_key_jwk});return b64(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},id.ecdsaPrivate,te.encode(d)))}
async function verify(row){if(!row?.envelope_signature||!row?.sender_public_key_jwk?.ecdsa)return false;const p=await crypto.subtle.importKey('jwk',row.sender_public_key_jwk.ecdsa,{name:'ECDSA',namedCurve:'P-256'},false,['verify']),d=stable({conversation_id:row.conversation_id,user_id:row.user_id,sender_user_id:row.sender_user_id,key_version:row.key_version,wrapped_key:row.wrapped_key,wrap_nonce:row.wrap_nonce,sender_public_key_jwk:row.sender_public_key_jwk});return crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},p,ub(row.envelope_signature),te.encode(d))}
async function unwrap(row){const id=window.kdE2EE.getIdentity(),wk=await crypto.subtle.importKey('raw',await crypto.subtle.deriveBits({name:'ECDH',public:await pub(row.sender_public_key_jwk.ecdh)},id.ecdhPrivate,256),{name:'AES-GCM'},false,['decrypt']),raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:ub(row.wrap_nonce),additionalData:te.encode('KD-E2EE-WRAP-v1')},wk,ub(row.wrapped_key));return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
const cache=new Map();
async function load(cid,v){const k=cid+':'+v;if(cache.has(k))return cache.get(k);const uid=await me();if(!uid)throw Error('Not authenticated');const r=await getSb().from('kd_conversation_key_epochs').select('*').eq('conversation_id',cid).eq('key_version',v).eq('user_id',uid).maybeSingle();if(r.error)throw r.error;if(!r.data)throw Error('E2EE key epoch unavailable');if(!(await verify(r.data)))throw Error('E2EE envelope signature invalid');const key=await unwrap(r.data);cache.set(k,key);return key}
async function members(cid){const r=await getSb().from('kd_conversation_members').select('user_id').eq('conversation_id',cid);if(r.error)throw r.error;return [...new Set((r.data||[]).map(x=>x.user_id))]}
async function establish(cid,v,ids,sender){const sb=getSb(),key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']),pubs=(await sb.from('kd_identity_keys').select('user_id,public_key_jwk,key_version').in('user_id',ids)).data||[];const by=new Map(pubs.map(x=>[x.user_id,x]));for(const uid of ids){const p=by.get(uid);if(!p?.public_key_jwk?.ecdh||!p?.public_key_jwk?.ecdsa)throw Error('Участник ещё не зарегистрировал ключи E2EE');const row={conversation_id:cid,user_id:uid,sender_user_id:sender,sender_public_key_jwk:{ecdh:window.kdE2EE.getIdentity().ecdhPublic,ecdsa:window.kdE2EE.getIdentity().ecdsaPublic},key_version:v,...await wrap(key,p.public_key_jwk.ecdh),envelope_signature_version:1};row.envelope_signature=await sign(row);const r=await sb.from('kd_conversation_key_epochs').insert(row);if(r.error&&!String(r.error.message||'').toLowerCase().includes('duplicate'))throw r.error}return{version:v,key}}
async function current(cid){await window.kdE2EE.ensure();const uid=await me();if(!uid)throw Error('Not authenticated');const c=(await getSb().from('kd_conversations').select('id,kind,created_by').eq('id',cid).maybeSingle()).data;if(!c)throw Error('Conversation not found');if(c.kind!=='direct')throw Error('Групповое E2EE ещё не активировано');const r=await getSb().from('kd_conversation_key_epochs').select('*').eq('conversation_id',cid).eq('user_id',uid).order('key_version',{ascending:false}).limit(1);if(r.error)throw r.error;if(r.data?.[0])return{version:r.data[0].key_version,key:await load(cid,r.data[0].key_version)};const ids=await members(cid);if(!ids.includes(uid))throw Error('Not a conversation member');if(c.created_by!==uid)throw Error('E2EE key is being established by the conversation initiator');return establish(cid,1,ids,uid)}
async function rotate(cid){await window.kdE2EE.ensure();const uid=await me();if(!uid)throw Error('Not authenticated');const c=(await getSb().from('kd_conversations').select('id,kind,created_by').eq('id',cid).maybeSingle()).data;if(!c||c.kind!=='direct')throw Error('Групповое E2EE ещё не активировано');if(c.created_by!==uid)throw Error('Только инициатор может ротировать E2EE-ключ');const q=await getSb().from('kd_conversation_key_epochs').select('key_version').eq('conversation_id',cid).order('key_version',{ascending:false}).limit(1);if(q.error)throw q.error;const v=Number(q.data?.[0]?.key_version||0)+1;return establish(cid,v,await members(cid),uid)}
async function enc(cid,text){const ep=await current(cid),nonce=crypto.getRandomValues(new Uint8Array(12)),aad=te.encode('KD-E2EE-v1:'+cid+':key-'+ep.version),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:aad},ep.key,te.encode(text));return{e2ee_version:1,e2ee_key_version:ep.version,ciphertext:b64(ct),cipher_nonce:b64(nonce),cipher_aad:b64(aad)}}
async function dec(cid,row){if(!row?.ciphertext)return row?.body??'';try{const v=Number(row.e2ee_key_version||1),key=await load(cid,v),aad=ub(row.cipher_aad);if(td.decode(aad)!=='KD-E2EE-v1:'+cid+':key-'+v)throw Error('AAD');return td.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:ub(row.cipher_nonce),additionalData:aad},key,ub(row.ciphertext)))}catch(e){return'🔒 Не удалось расшифровать сообщение'}}
function install(){if(window.__kdE2EEEpochsInstalled||!window.kdE2EE)return false;const base=window.kdE2EE;window.kdE2EE={...base,conversationKey:(cid,v)=>v?load(cid,v):current(cid),rotate,encryptText:enc,decryptText:dec};window.__kdE2EEEpochsInstalled=true;return true}
window.__kdInstallE2EEEpochs=install;
if(document.readyState==='complete')setTimeout(install,0);else window.addEventListener('load',()=>setTimeout(install,100));
})();