(()=>{
const sb=window.supabase.createClient('https://qqofizfqkctycyeafgsa.supabase.co','sb_publishable_MTZuMyuzb0XdtBy3GZIQZw_pHbXc9xK');
const $=q=>document.querySelector(q);
async function uid(){return (await sb.auth.getSession()).data.session?.user?.id}
async function ensure(){const u=await uid();if(!u)return null;const {data,error}=await sb.from('kd_profiles').select('id').eq('id',u).maybeSingle();return error?null:u}
async function addFavorite(messageId){const u=await ensure();if(!u)return;const {error}=await sb.from('kd_favorites').upsert({user_id:u,message_id:messageId},{onConflict:'user_id,message_id'});if(!error)toast('⭐ Добавлено в избранное');else toast('Не удалось сохранить')}
async function removeFavorite(messageId){const u=await uid();if(!u)return;const {error}=await sb.from('kd_favorites').delete().eq('user_id',u).eq('message_id',messageId);if(!error)toast('Убрано из избранного')}
async function loadFavorites(){const u=await uid();if(!u)return[];const {data}=await sb.from('kd_favorites').select('message_id,created_at,kd_messages(id,body,created_at,sender_id)').eq('user_id',u).order('created_at',{ascending:false});return data||[]}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1600)}
function openFavorites(){loadFavorites().then(rows=>{const box=document.createElement('div');box.className='kd-modal';box.innerHTML='<div class="kd-modal-card"><div class="kd-modal-head"><b>⭐ Избранное</b><button>×</button></div><div class="kd-fav-list"></div></div>';const list=box.querySelector('.kd-fav-list');rows.forEach(r=>{const m=r.kd_messages;if(!m)return;const item=document.createElement('button');item.className='kd-fav-item';item.innerHTML=`<span>⭐</span><span><b>${new Date(m.created_at).toLocaleString('ru-RU')}</b><small>${escapeHtml(m.body||'')}</small></span>`;item.onclick=()=>{box.remove();document.querySelector(`[data-message-id="${m.id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})};list.appendChild(item)});if(!rows.length)list.innerHTML='<div class="kd-empty">Здесь будут сохранённые сообщения</div>';box.querySelector('button').onclick=()=>box.remove();document.body.appendChild(box)})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function wire(){const side=document.querySelector('.sidebar-bottom');if(side&&!document.querySelector('.kd-fav-btn')){const b=document.createElement('button');b.className='bottom-btn kd-fav-btn';b.innerHTML='⭐ <span>Избранное</span>';b.onclick=openFavorites;side.prepend(b)}document.addEventListener('contextmenu',e=>{const m=e.target.closest('.msg');if(!m)return;const id=m.dataset.messageId;if(!id)return;setTimeout(()=>{if(confirm('Добавить это сообщение в Избранное?'))addFavorite(id)},20)})}
setTimeout(wire,1500);window.kdAddFavorite=addFavorite;window.kdRemoveFavorite=removeFavorite;window.kdOpenFavorites=openFavorites;
})();
