(()=>{const wait=()=>window.user&&window.sb;setTimeout(()=>{if(!wait())return;const sb=window.sb,user=window.user;const css=document.createElement('style');css.textContent='.msg{position:relative}.msg-tools{position:absolute;right:-6px;top:-28px;display:none;gap:3px;padding:3px;background:#111118;border:1px solid #292936;border-radius:10px;z-index:5}.msg:hover .msg-tools{display:flex}.msg.out .msg-tools{right:auto;left:-6px}.msg-tools button{border:0;background:transparent;color:#aaa;cursor:pointer;font-size:11px;padding:3px}.msg-tools button:hover{color:#fff}.msg-actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:5px}.msg-actions button{border:1px solid #333;background:#15151e;color:#ddd;border-radius:9px;padding:3px 6px;font-size:11px;cursor:pointer}.msg-edited{font-size:8px;opacity:.55;margin-left:3px}.profile-form label{display:block;color:#777;font-size:9px;margin-top:8px}.profile-form textarea{width:100%;min-height:70px;resize:vertical;box-sizing:border-box;padding:12px;border-radius:12px;background:#0b0d13;color:#fff;border:1px solid #303442;margin-top:5px}.profile-save{width:100%;padding:12px;border:0;border-radius:12px;background:#7865ff;color:#fff;font-weight:800;margin-top:12px}';document.head.appendChild(css);
const toast=x=>{const t=document.querySelector('#toast');if(t){t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function reaction(id,emoji){const {data:old}=await sb.from('kd_message_reactions').select('message_id').eq('message_id',id).eq('user_id',user.id).eq('reaction',emoji).maybeSingle();const r=old?await sb.from('kd_message_reactions').delete().eq('message_id',id).eq('user_id',user.id).eq('reaction',emoji):await sb.from('kd_message_reactions').insert({message_id:id,user_id:user.id,reaction:emoji});if(r.error)toast(r.error.message);else renderReactions(id)}
async function renderReactions(id){const r=await sb.from('kd_message_reactions').select('reaction,user_id').eq('message_id',id);const el=document.querySelector(`[data-message-id="${id}"]`);if(!el)return;let box=el.querySelector('.msg-actions');if(!box){box=document.createElement('div');box.className='msg-actions';el.querySelector('.bubble').after(box)}const counts={};(r.data||[]).forEach(x=>counts[x.reaction]=(counts[x.reaction]||0)+1);box.innerHTML=Object.entries(counts).map(([e,n])=>`<button data-r="${esc(e)}">${e} ${n}</button>`).join('')+'<button data-r="➕">➕</button>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>reaction(id,b.dataset.r));}
async function editMessage(id,current){const next=prompt('Изменить сообщение:',current);if(next===null||!next.trim()||next.trim()===current)return;const r=await sb.from('kd_messages').update({body:next.trim(),edited_at:new Date().toISOString()}).eq('id',id).eq('sender_id',user.id);if(r.error)toast(r.error.message);else location.reload()}
async function deleteMessage(id){if(!confirm('Удалить сообщение?'))return;const r=await sb.from('kd_messages').update({deleted_at:new Date().toISOString(),body:'Сообщение удалено'}).eq('id',id).eq('sender_id',user.id);if(r.error)toast(r.error.message);else{const el=document.querySelector(`[data-message-id="${id}"]`);if(el){el.querySelector('.bubble').textContent='Сообщение удалено';el.style.opacity='.55'}}}
function attachTools(el){if(el.querySelector('.msg-tools'))return;const id=el.dataset.messageId;const bubble=el.querySelector('.bubble');const own=el.classList.contains('out');const tools=document.createElement('div');tools.className='msg-tools';tools.innerHTML='<button data-act="reply">↩</button><button data-act="react">😊</button>'+(own?'<button data-act="edit">✎</button><button data-act="delete">🗑</button>':'');bubble.parentElement.appendChild(tools);tools.querySelector('[data-act="react"]').onclick=()=>reaction(id,'❤️');tools.querySelector('[data-act="edit"]')?.addEventListener('click',()=>editMessage(id,bubble.textContent));tools.querySelector('[data-act="delete"]')?.addEventListener('click',()=>deleteMessage(id));tools.querySelector('[data-act="reply"]').onclick=()=>{window.kdReplyTo=id;const input=document.querySelector('#messageInput');if(input){input.focus();input.placeholder='Ответ на сообщение…'}};renderReactions(id)}
const mo=new MutationObserver(()=>document.querySelectorAll('.msg').forEach(attachTools));mo.observe(document.body,{childList:true,subtree:true});document.querySelectorAll('.msg').forEach(attachTools);
async function profileModal(){const m=document.createElement('div');m.className='kd-modal';m.innerHTML=`<div class="kd-modal-card profile-form"><button class="kd-close">×</button><h2>Мой профиль</h2><label>Имя</label><input id="pfName" value="${esc(user.profile?.display_name||'')}"><label>Username</label><input id="pfUser" value="${esc(user.profile?.username||'')}"><label>О себе</label><textarea id="pfBio"></textarea><button class="profile-save">Сохранить</button></div>`;document.body.appendChild(m);const p=await sb.from('kd_profiles').select('display_name,username,bio').eq('id',user.id).single();if(p.data){m.querySelector('#pfName').value=p.data.display_name||'';m.querySelector('#pfUser').value=p.data.username||'';m.querySelector('#pfBio').value=p.data.bio||''}m.querySelector('.kd-close').onclick=()=>m.remove();m.querySelector('.profile-save').onclick=async()=>{const name=m.querySelector('#pfName').value.trim(),username=m.querySelector('#pfUser').value.trim().replace(/^@/,'').toLowerCase(),bio=m.querySelector('#pfBio').value.trim();if(!/^[a-z0-9_]{3,32}$/.test(username)){toast('Username: 3–32 символа, a-z, 0-9, _');return}const r=await sb.from('kd_profiles').update({display_name:name||'KD User',username,bio}).eq('id',user.id);if(r.error)toast(r.error.message);else{m.remove();location.reload()}}}
const pb=document.querySelector('#profileBtn');if(pb){pb.onclick=profileModal}
},800)})();