(()=>{
'use strict';
let sb=null, channel=null, refreshTimer=null;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const toast=m=>{const e=document.getElementById('toast');if(e){e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}};
function active(){return window.kdActiveConversation||null}
async function ready(){if(sb)return sb; for(let i=0;i<40&&!window.supabase;i++)await new Promise(r=>setTimeout(r,250)); if(!window.supabase)return null; const K=window.KD_SUPABASE_KEY||'sb_publishable_MTZuMyuzb0XdtBy3ZGIQZw_pHbXc9xK'; sb=window.supabase.createClient('https://qqofizfqkctycyeafgsa.supabase.co',K);return sb}
async function isGroup(c){if(!c)return false;const s=await ready();if(!s)return false;const {data}=await s.from('kd_conversations').select('kind').eq('id',c).maybeSingle();return data?.kind==='group'}
function ensureStyles(){if(document.getElementById('kdPollStyle'))return;const st=document.createElement('style');st.id='kdPollStyle';st.textContent=`.kd-poll-wrap{padding:10px 14px 4px}.kd-poll-card{max-width:560px;margin:8px auto;padding:16px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(22,22,31,.94);box-shadow:0 8px 28px rgba(0,0,0,.18)}.kd-poll-q{font-weight:800;font-size:16px;line-height:1.3}.kd-poll-meta{font-size:11px;opacity:.55;margin:5px 0 12px}.kd-poll-option{position:relative;width:100%;margin:7px 0;padding:10px 12px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:rgba(255,255,255,.035);color:inherit;text-align:left;cursor:pointer;overflow:hidden}.kd-poll-option .bar{position:absolute;inset:0 auto 0 0;background:rgba(120,150,255,.16);width:var(--p);pointer-events:none}.kd-poll-option .row{position:relative;display:flex;gap:8px;justify-content:space-between;z-index:1}.kd-poll-option.selected{border-color:rgba(120,150,255,.7)}.kd-poll-foot{display:flex;justify-content:space-between;gap:8px;margin-top:10px;font-size:11px;opacity:.62}.kd-poll-close{border:0;background:transparent;color:inherit;cursor:pointer}.kd-poll-create{display:flex;gap:6px;align-items:center}.kd-poll-create button{border:0;border-radius:10px;padding:8px 10px;cursor:pointer}`;document.head.appendChild(st)}
async function load(){const c=active();if(!c)return;const group=await isGroup(c);const old=document.getElementById('kdPollWrap');if(old)old.remove();if(!group)return;const s=await ready();if(!s)return;const {data:polls}=await s.from('kd_group_polls').select('*').eq('conversation_id',c).order('created_at',{ascending:true});if(!polls?.length)return;const wrap=document.createElement('div');wrap.id='kdPollWrap';wrap.className='kd-poll-wrap';for(const p of polls){const {data:opts}=await s.from('kd_group_poll_options').select('*').eq('poll_id',p.id).order('position');const {data:votes}=await s.from('kd_group_poll_votes').select('option_id,user_id').eq('poll_id',p.id);renderPoll(wrap,p,opts||[],votes||[])}const msg=document.getElementById('messages');if(msg)msg.appendChild(wrap);}
function renderPoll(w,p,opts,votes){const card=document.createElement('div');card.className='kd-poll-card';const counts={};votes.forEach(v=>counts[v.option_id]=(counts[v.option_id]||0)+1);const total=votes.length;const mine=new Set(votes.filter(v=>v.user_id===sb.auth.currentUser?.id).map(v=>v.option_id));card.innerHTML=`<div class="kd-poll-q">📊 ${esc(p.question)}</div><div class="kd-poll-meta">${p.multiple_choice?'Можно выбрать несколько':'Один вариант'} · ${p.closed?'Опрос закрыт':'Голосование открыто'}</div>`;opts.forEach(o=>{const n=counts[o.id]||0,pc=total?Math.round(n*100/total):0;const b=document.createElement('button');b.className='kd-poll-option'+(mine.has(o.id)?' selected':'');b.style.setProperty('--p',pc+'%');b.innerHTML=`<span class="bar"></span><span class="row"><span>${mine.has(o.id)?'✓ ':''}${esc(o.option_text)}</span><b>${pc}% · ${n}</b></span>`;b.onclick=()=>vote(p,o.id,mine,opts);card.appendChild(b)});const foot=document.createElement('div');foot.className='kd-poll-foot';foot.innerHTML=`<span>${total} ${total===1?'голос':'голосов'}</span>`;if(!p.closed&&(p.created_by===sb.auth.currentUser?.id)){const close=document.createElement('button');close.className='kd-poll-close';close.textContent='Закрыть';close.onclick=async()=>{await sb.rpc('kd_close_group_poll',{p_poll_id:p.id});load()};foot.appendChild(close)}card.appendChild(foot);w.appendChild(card)}
async function vote(p,id,mine,opts){if(p.closed)return;const next=new Set(mine);if(p.multiple_choice){next.has(id)?next.delete(id):next.add(id)}else{next.clear();next.add(id)}const {error}=await sb.rpc('kd_set_group_poll_votes',{p_poll_id:p.id,p_option_ids:[...next]});if(error)toast(error.message||'Не удалось проголосовать');else load()}
async function createPoll(){const c=active();if(!(await isGroup(c)))return toast('Опросы доступны только в группах');const q=prompt('Вопрос опроса');if(!q?.trim())return;const raw=prompt('Варианты через запятую (минимум 2)');const opts=(raw||'').split(',').map(x=>x.trim()).filter(Boolean);if(opts.length<2)return toast('Нужно минимум 2 варианта');const multiple=confirm('Разрешить выбирать несколько вариантов?');const s=await ready();const {error}=await s.rpc('kd_create_group_poll',{p_conversation_id:c,p_question:q.trim(),p_options:opts,p_multiple:multiple});if(error)toast(error.message||'Ошибка создания');else{toast('Опрос создан');load()}}
function bind(){ensureStyles();const top=document.querySelector('.top-actions');if(top&&!document.getElementById('kdPollBtn')){const b=document.createElement('button');b.id='kdPollBtn';b.className='icon-btn';b.title='Создать опрос';b.textContent='📊';b.onclick=createPoll;top.insertBefore(b,top.lastElementChild)}if(!refreshTimer)refreshTimer=setInterval(()=>{if(active())load()},4000)}
async function realtime(){const s=await ready();const c=active();if(!s||!c)return;if(channel)await s.removeChannel(channel);channel=s.channel('kd-group-polls-'+c).on('postgres_changes',{event:'*',schema:'public',table:'kd_group_polls',filter:'conversation_id=eq.'+c},load).on('postgres_changes',{event:'*',schema:'public',table:'kd_group_poll_votes'},load).subscribe()}
function init(){bind();setInterval(()=>{bind();const c=active();if(c&&c!==window.__kdPollConv){window.__kdPollConv=c;load();realtime()}},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.kdOpenGroupPolls=load;})();