(()=>{
'use strict';
let sb=null, channel=null, refreshTimer=null, loading=false;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const toast=m=>{const e=document.getElementById('toast');if(e){e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}};
function active(){return window.kdActiveConversation||null}
async function ready(){if(sb)return sb;for(let i=0;i<40&&!window.supabase;i++)await new Promise(r=>setTimeout(r,250));if(!window.supabase)return null;const K=window.KD_SUPABASE_KEY||'sb_publishable_MTZuMyuzb0XdtBy3ZGIQZw_pHbXc9xK';sb=window.supabase.createClient('https://qqofizfqkctycyeafgsa.supabase.co',K);return sb}
async function isGroup(c){if(!c)return false;const s=await ready();if(!s)return false;const {data}=await s.from('kd_conversations').select('kind').eq('id',c).maybeSingle();return data?.kind==='group'}
function fmtDate(v){try{return new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return ''}}
function ensureStyles(){if(document.getElementById('kdPollStyle'))return;const st=document.createElement('style');st.id='kdPollStyle';st.textContent=`.kd-poll-wrap{padding:10px 14px 8px}.kd-poll-card{max-width:560px;margin:10px auto;padding:16px;border:1px solid rgba(255,255,255,.1);border-radius:20px;background:rgba(22,22,31,.94);box-shadow:0 8px 28px rgba(0,0,0,.18);animation:kdPollIn .22s ease both}.kd-poll-card:hover{border-color:rgba(120,150,255,.24)}@keyframes kdPollIn{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}.kd-poll-head{display:flex;gap:10px;align-items:center}.kd-poll-avatar{width:34px;height:34px;border-radius:50%;object-fit:cover;background:rgba(255,255,255,.08);flex:none}.kd-poll-author{font-size:12px;font-weight:700}.kd-poll-time{font-size:10px;opacity:.48;margin-top:2px}.kd-poll-q{font-weight:800;font-size:16px;line-height:1.3;margin-top:11px}.kd-poll-meta{font-size:11px;opacity:.55;margin:5px 0 12px}.kd-poll-option{position:relative;width:100%;margin:7px 0;padding:11px 12px;border:1px solid rgba(255,255,255,.1);border-radius:13px;background:rgba(255,255,255,.035);color:inherit;text-align:left;cursor:pointer;overflow:hidden;transition:transform .12s,border-color .12s,background .12s}.kd-poll-option:hover{transform:translateY(-1px);background:rgba(255,255,255,.06)}.kd-poll-option:active{transform:scale(.985)}.kd-poll-option .bar{position:absolute;inset:0 auto 0 0;background:rgba(120,150,255,.16);width:var(--p);pointer-events:none;transition:width .25s ease}.kd-poll-option .row{position:relative;display:flex;gap:8px;justify-content:space-between;z-index:1}.kd-poll-option.selected{border-color:rgba(120,150,255,.7);box-shadow:inset 0 0 0 1px rgba(120,150,255,.12)}.kd-poll-foot{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:11px;font-size:11px;opacity:.62}.kd-poll-close{border:0;background:rgba(255,255,255,.06);color:inherit;border-radius:9px;padding:6px 9px;cursor:pointer}.kd-poll-close:hover{background:rgba(255,255,255,.1)}.kd-poll-create{display:flex;gap:6px;align-items:center}.kd-poll-create button{border:0;border-radius:10px;padding:8px 10px;cursor:pointer}.kd-poll-empty{max-width:560px;margin:8px auto;text-align:center;font-size:12px;opacity:.45;padding:12px}`;document.head.appendChild(st)}
async function load(){const c=active();if(!c||loading)return;loading=true;try{const group=await isGroup(c);const old=document.getElementById('kdPollWrap');if(old)old.remove();if(!group)return;const s=await ready();if(!s)return;const [{data:polls},{data:members}]=await Promise.all([s.from('kd_group_polls').select('*').eq('conversation_id',c).order('created_at',{ascending:true}),s.from('kd_conversation_members').select('user_id').eq('conversation_id',c)]);if(!polls?.length)return;const ids=(members||[]).map(x=>x.user_id);let profiles=[];if(ids.length) {const r=await s.from('kd_profiles').select('id,display_name,username,avatar_url').in('id',ids);profiles=r.data||[]}const pmap=new Map(profiles.map(x=>[x.id,x]));const wrap=document.createElement('div');wrap.id='kdPollWrap';wrap.className='kd-poll-wrap';for(const p of polls){const [{data:opts},{data:votes}]=await Promise.all([s.from('kd_group_poll_options').select('*').eq('poll_id',p.id).order('position'),s.from('kd_group_poll_votes').select('option_id,user_id').eq('poll_id',p.id)]);renderPoll(wrap,p,opts||[],votes||[],pmap.get(p.created_by));}const msg=document.getElementById('messages');if(msg)msg.appendChild(wrap)}finally{loading=false}}
function renderPoll(w,p,opts,votes,creator){const card=document.createElement('div');card.className='kd-poll-card';const counts={};votes.forEach(v=>counts[v.option_id]=(counts[v.option_id]||0)+1);const total=votes.length;const me=sb.auth.currentUser?.id;const mine=new Set(votes.filter(v=>v.user_id===me).map(v=>v.option_id));const name=creator?.display_name||creator?.username||'Участник группы';const avatar=creator?.avatar_url||'';card.innerHTML=`<div class="kd-poll-head">${avatar?`<img class="kd-poll-avatar" src="${esc(avatar)}">`:'<div class="kd-poll-avatar">📊</div>'}<div><div class="kd-poll-author">${esc(name)}</div><div class="kd-poll-time">${fmtDate(p.created_at)}</div></div></div><div class="kd-poll-q">📊 ${esc(p.question)}</div><div class="kd-poll-meta">${p.multiple_choice?'Можно выбрать несколько':'Один вариант'} · ${p.closed?'Опрос закрыт':'Голосование открыто'}</div>`;opts.forEach(o=>{const n=counts[o.id]||0,pc=total?Math.round(n*100/total):0;const b=document.createElement('button');b.className='kd-poll-option'+(mine.has(o.id)?' selected':'');b.style.setProperty('--p',pc+'%');b.innerHTML=`<span class="bar"></span><span class="row"><span>${mine.has(o.id)?'✓ ':''}${esc(o.option_text)}</span><b>${pc}% · ${n}</b></span>`;b.onclick=()=>vote(p,o.id,mine);card.appendChild(b)});const foot=document.createElement('div');foot.className='kd-poll-foot';foot.innerHTML=`<span>${total} ${total===1?'голос':'голосов'}</span>`;if(!p.closed){const rolePromise=sb.from('kd_conversation_members').select('role').eq('conversation_id',p.conversation_id).eq('user_id',me).maybeSingle();rolePromise.then(({data:m})=>{if(p.created_by===me||m?.role==='owner'||m?.role==='admin'){const close=document.createElement('button');close.className='kd-poll-close';close.textContent='Закрыть';close.onclick=async()=>{const {error}=await sb.rpc('kd_close_group_poll',{p_poll_id:p.id});if(error)toast(error.message||'Не удалось закрыть');else load()};foot.appendChild(close)}})}card.appendChild(foot);w.appendChild(card)}
async function vote(p,id,mine){if(p.closed)return;const next=new Set(mine);if(p.multiple_choice){next.has(id)?next.delete(id):next.add(id)}else{next.clear();next.add(id)}const {error}=await sb.rpc('kd_set_group_poll_votes',{p_poll_id:p.id,p_option_ids:[...next]});if(error)toast(error.message||'Не удалось проголосовать');else load()}
async function createPoll(){const c=active();if(!(await isGroup(c)))return toast('Опросы доступны только в группах');const q=prompt('Вопрос опроса');if(!q?.trim())return;const raw=prompt('Варианты через запятую (минимум 2)');const opts=(raw||'').split(',').map(x=>x.trim()).filter(Boolean);if(opts.length<2)return toast('Нужно минимум 2 варианта');const multiple=confirm('Разрешить выбирать несколько вариантов?');const s=await ready();const {error}=await s.rpc('kd_create_group_poll',{p_conversation_id:c,p_question:q.trim(),p_options:opts,p_multiple:multiple});if(error)toast(error.message||'Ошибка создания');else{toast('Опрос создан');load()}}
function bind(){ensureStyles();const top=document.querySelector('.top-actions');if(top&&!document.getElementById('kdPollBtn')){const b=document.createElement('button');b.id='kdPollBtn';b.className='icon-btn';b.title='Создать опрос';b.textContent='📊';b.onclick=createPoll;top.insertBefore(b,top.lastElementChild)}if(!refreshTimer)refreshTimer=setInterval(()=>{if(active())load()},6000)}
async function realtime(){const s=await ready();const c=active();if(!s||!c)return;if(channel)await s.removeChannel(channel);channel=s.channel('kd-group-polls-'+c).on('postgres_changes',{event:'*',schema:'public',table:'kd_group_polls',filter:'conversation_id=eq.'+c},load).on('postgres_changes',{event:'*',schema:'public',table:'kd_group_poll_votes'},load).subscribe()}
function init(){bind();setInterval(()=>{bind();const c=active();if(c&&c!==window.__kdPollConv){window.__kdPollConv=c;load();realtime()}},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.kdOpenGroupPolls=load;})();