(()=>{setTimeout(async()=>{if(!window.supabase)return;const SB_URL='https://qqofizfqkctycyeafgsa.supabase.co',SB_KEY='sb_publishable_MTZuMyuzb0XdtBy3ZGIQZw_pHbXc9xK',sb=window.supabase.createClient(SB_URL,SB_KEY),session=(await sb.auth.getSession()).data.session;if(!session)return;const user=session.user,$=s=>document.querySelector(s),toast=x=>{const t=$('#toast');if(t){t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}};let pendingFiles=[],recording=null,recordingChunks=[],recordStarted=0,voiceBlob=null,voiceDuration=0;
const css=document.createElement('style');css.textContent='.media-file{margin-top:7px;border-radius:12px;overflow:hidden}.media-file img{display:block;max-width:min(280px,100%);max-height:320px;object-fit:cover;border-radius:12px}.media-file a{display:flex;align-items:center;gap:8px;color:inherit;text-decoration:none;padding:9px 11px;background:#ffffff0b;border:1px solid #ffffff12;border-radius:11px}.media-file audio{display:block;width:min(280px,100%);height:38px}.media-name{font-size:11px;opacity:.8;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.attach-preview{display:flex;gap:6px;flex-wrap:wrap;padding:0 12px 6px}.attach-chip{display:flex;align-items:center;gap:5px;background:#15151e;border:1px solid #30303d;color:#ddd;border-radius:9px;padding:5px 8px;font-size:10px}.attach-chip button{border:0;background:none;color:#aaa;cursor:pointer}.voice-recording{display:flex;align-items:center;gap:8px;padding:6px 10px;margin:0 10px 6px;background:#21151b;border:1px solid #59303a;border-radius:10px;color:#ff9aa5;font-size:11px}.voice-recording button{margin-left:auto;border:0;border-radius:8px;background:#3a2028;color:#fff;padding:5px 8px}.voice-btn.recording{background:#ff5969!important;color:#fff!important}';document.head.appendChild(css);
const composer=$('#composer'),attach=$('#attach'),emoji=$('#emoji');if(!composer||!attach)return;
const fileInput=document.createElement('input');fileInput.type='file';fileInput.multiple=true;fileInput.hidden=true;fileInput.accept='image/*,.pdf,.txt,.zip,audio/*';document.body.appendChild(fileInput);
const voiceBtn=document.createElement('button');voiceBtn.type='button';voiceBtn.id='voice';voiceBtn.className='emoji-btn voice-btn';voiceBtn.textContent='🎙';emoji?.before(voiceBtn);
const preview=document.createElement('div');preview.className='attach-preview';composer.before(preview);
function renderPreview(){preview.innerHTML=pendingFiles.map((f,i)=>'<div class="attach-chip">'+(f.type.startsWith('image/')?'🖼️':f.type.startsWith('audio/')?'🎵':'📎')+' '+String(f.name).replace(/[<>]/g,'').slice(0,28)+' <button data-i="'+i+'">×</button></div>').join('');preview.querySelectorAll('button').forEach(b=>b.onclick=()=>{pendingFiles.splice(+b.dataset.i,1);renderPreview()})}
attach.onclick=()=>fileInput.click();fileInput.onchange=()=>{pendingFiles=[...pendingFiles,...fileInput.files].slice(0,6);fileInput.value='';renderPreview()};
async function uploadBlob(blob,path,type){const r=await sb.storage.from('kd-messenger').upload(path,blob,{contentType:type,upsert:false});if(r.error)throw r.error;return path}
async function currentConversation(){const el=document.querySelector('.chat.active');return el?.dataset.id||null}
async function insertMedia(conversationId,file,caption='',duration=null){if(!conversationId)throw new Error('Откройте чат');if(file.size>50*1024*1024)throw new Error('Файл больше 50 МБ');const ext=(file.name?.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,8)||'bin';const path=conversationId+'/'+user.id+'/'+crypto.randomUUID()+'.'+ext;await uploadBlob(file,path,file.type||'application/octet-stream');const r=await sb.from('kd_messages').insert({conversation_id:conversationId,sender_id:user.id,body:caption||'',message_type:file.type?.startsWith('audio/')?'voice':'file',attachment_path:path,attachment_name:file.name||'voice.webm',attachment_type:file.type||'application/octet-stream',attachment_size:file.size,voice_duration:duration}).select().single();if(r.error){await sb.storage.from('kd-messenger').remove([path]);throw r.error}return r.data}
async function appendMediaMessage(m){const box=$('#messages');if(!box||document.querySelector('[data-message-id="'+m.id+'"]'))return;const el=document.createElement('div');el.className='msg out';el.dataset.messageId=m.id;el.innerHTML='<div class="bubble">'+(m.body?'<div class="media-caption"></div>':'')+'</div><div class="msg-meta">сейчас ✓✓</div>';if(m.body)el.querySelector('.media-caption').textContent=m.body;box.appendChild(el);await decorate(el,m);box.scrollTop=box.scrollHeight}
async function decorate(el,m){if(!m?.id)return;const r=await sb.from('kd_messages').select('attachment_path,attachment_name,attachment_type,attachment_size,voice_duration,body,message_type').eq('id',m.id).maybeSingle();const d=r.data;if(!d?.attachment_path)return;const u=await sb.storage.from('kd-messenger').createSignedUrl(d.attachment_path,3600);if(u.error||!u.data?.signedUrl)return;const wrap=document.createElement('div');wrap.className='media-file';const type=d.attachment_type||'';if(type.startsWith('image/'))wrap.innerHTML='<a href="'+u.data.signedUrl+'" target="_blank" rel="noreferrer"><img loading="lazy" src="'+u.data.signedUrl+'" alt="'+String(d.attachment_name||'Фото').replace(/[<>"]/g,'')+'"></a>';else if(type.startsWith('audio/')){const musicData={id:m.id,attachment_path:d.attachment_path,attachment_name:d.attachment_name,attachment_type:type};const player=window.kdRenderMusicMessage?.(musicData);if(player)wrap.appendChild(player);else wrap.innerHTML='<audio controls preload="metadata" src="'+u.data.signedUrl+'"></audio>'}else wrap.innerHTML='<a href="'+u.data.signedUrl+'" target="_blank" rel="noreferrer">📎 <span class="media-name">'+String(d.attachment_name||'Файл').replace(/[<>"]/g,'')+'</span></a>';el.querySelector('.bubble')?.appendChild(wrap)}
async function decorateAll(){for(const el of document.querySelectorAll('.msg[data-message-id]')){if(el.querySelector('.media-file'))continue;await decorate(el,{id:el.dataset.messageId})}}
new MutationObserver(()=>{clearTimeout(window.__kdMediaTimer);window.__kdMediaTimer=setTimeout(decorateAll,80)}).observe($('#messages')||document.body,{childList:true,subtree:true});setTimeout(decorateAll,500);
async function recordVoice(){if(recording)return;const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';recording=new MediaRecorder(stream,{mimeType:mime});recordingChunks=[];recordStarted=Date.now();const bar=document.createElement('div');bar.className='voice-recording';bar.id='voiceRecording';bar.innerHTML='<span>● Запись голоса <b>0:00</b></span><button type="button">Готово</button>';composer.before(bar);const tick=setInterval(()=>{const s=Math.floor((Date.now()-recordStarted)/1000);bar.querySelector('b').textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0')},250);bar.querySelector('button').onclick=()=>recording?.stop();recording.ondataavailable=e=>{if(e.data.size)recordingChunks.push(e.data)};recording.onstop=()=>{clearInterval(tick);stream.getTracks().forEach(t=>t.stop());voiceDuration=Math.max(1,Math.round((Date.now()-recordStarted)/1000));voiceBlob=new Blob(recordingChunks,{type:mime});recording=null;bar.remove();voiceBtn.classList.remove('recording');toast('Голосовое готово — нажми отправить')};recording.start();voiceBtn.classList.add('recording')}
voiceBtn.onclick=async()=>{try{if(recording){recording.stop();return}if(!navigator.mediaDevices?.getUserMedia)throw new Error('Запись голоса не поддерживается');await recordVoice()}catch(e){toast(e.message||'Нет доступа к микрофону')}};
composer.addEventListener('submit',async e=>{if(!pendingFiles.length&&!voiceBlob)return;e.preventDefault();e.stopImmediatePropagation();const cid=await currentConversation();if(!cid){toast('Сначала откройте чат');return}const input=$('#messageInput'),caption=input?.value.trim()||'';try{if(voiceBlob){const file=new File([voiceBlob],'voice-'+Date.now()+'.webm',{type:voiceBlob.type||'audio/webm'});const m=await insertMedia(cid,file,caption,voiceDuration);await appendMediaMessage(m);voiceBlob=null;voiceDuration=0}for(const f of pendingFiles){const m=await insertMedia(cid,f,caption);await appendMediaMessage(m)}pendingFiles=[];renderPreview();if(input)input.value='';toast('Отправлено')}catch(err){toast(err.message||'Не удалось отправить файл')}},true);
window.kdSendMedia=insertMedia;window.kdDecorateMedia=decorateAll;},900)})();