(()=>{
'use strict';
const SUPA_URL='https://qqofizfqkctycyeafgsa.supabase.co';
const SUPA_KEY='sb_publishable_MTZuMyuzb0XdtBy3GZIQZw_pHbXc9xK';
const sb=window.supabase?.createClient(SUPA_URL,SUPA_KEY);
if(!sb)return;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[c]));
let current=null;
function toast(t){const x=document.querySelector('#toast');if(x){x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}}
function panel(){if(document.querySelector('#kdMemoryPanel'))return;const d=document.createElement('div');d.id='kdMemoryPanel';d.innerHTML='<div class="kd-memory-backdrop"></div><section class="kd-memory-card"><header><div><b>🧠 KD Memory</b><small>Память этого чата</small></div><button id="kdMemoryClose">×</button></header><div id="kdMemoryBody"><div class="kd-memory-empty">Загрузка памяти…</div></div><footer><button id="kdMemoryAdd">＋ Добавить</button><button id="kdMemoryClear">Очистить</button></footer></section></div>';document.body.appendChild(d);d.querySelector('#kdMemoryClose').onclick=close;d.querySelector('.kd-memory-backdrop').onclick=close;d.querySelector('#kdMemoryAdd').onclick=add;d.querySelector('#kdMemoryClear').onclick=clearAll}
function close(){document.querySelector('#kdMemoryPanel')?.remove()}
async function get(){if(!current)return[];const {data,error}=await sb.from('kd_memory').select('id,memory,created_at').eq('conversation_id',current).order('created_at',{ascending:false});if(error){toast('Память пока недоступна');return[]}return data||[]}
async function render(){const b=document.querySelector('#kdMemoryBody');if(!b)return;const rows=await get();b.innerHTML=rows.length?rows.map(r=>`<div class="kd-memory-item"><span>${esc(r.memory)}</span><button data-id="${r.id}">×</button></div>`).join(''):'<div class="kd-memory-empty">Память пока пустая.<br><small>Добавляй важные факты вручную — AI сможет использовать их позже.</small></div>';b.querySelectorAll('button[data-id]').forEach(x=>x.onclick=async()=>{const {error}=await sb.from('kd_memory').delete().eq('id',x.dataset.id);if(error)toast('Не удалось удалить');else render()})}
async function add(value){if(!current)return;const v=(typeof value==='string'?value:prompt('Что сохранить в памяти этого чата?'))?.trim();if(!v)return;const {data:u}=await sb.auth.getUser();if(!u?.user)return;const {error}=await sb.from('kd_memory').insert({conversation_id:current,user_id:u.user.id,memory:v});if(error)toast('Не удалось сохранить');else{toast('Сохранено 🧠');render()}}
async function clearAll(){if(!current||!confirm('Очистить память этого чата?'))return;const {error}=await sb.from('kd_memory').delete().eq('conversation_id',current);if(error)toast('Не удалось очистить');else{toast('Память очищена');render()}}
async function open(){current=window.kdActiveConversation;if(!current){toast('Сначала открой чат');return}panel();await render()}
function button(){const t=document.querySelector('.top-actions');if(!t||document.querySelector('#kdMemoryBtn'))return;const b=document.createElement('button');b.id='kdMemoryBtn';b.className='icon-btn';b.title='KD Memory';b.textContent='🧠';b.onclick=open;t.prepend(b)}
const css=document.createElement('style');css.textContent=`#kdMemoryPanel{position:fixed;inset:0;z-index:100;display:grid;place-items:center}.kd-memory-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.62);backdrop-filter:blur(7px)}.kd-memory-card{position:relative;width:min(460px,calc(100vw - 28px));max-height:min(620px,82vh);display:flex;flex-direction:column;background:#101016;border:1px solid rgba(255,255,255,.1);border-radius:22px;box-shadow:0 30px 100px rgba(0,0,0,.5);overflow:hidden}.kd-memory-card header,.kd-memory-card footer{padding:16px 18px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.06)}.kd-memory-card footer{border-top:1px solid rgba(255,255,255,.06);border-bottom:0;gap:8px}.kd-memory-card header b{display:block;font-size:14px}.kd-memory-card header small{display:block;color:#777;font-size:9px;margin-top:4px}.kd-memory-card header button{border:0;background:transparent;color:#aaa;font-size:24px;cursor:pointer}.kd-memory-card footer button{flex:1;border:1px solid rgba(255,255,255,.08);background:#181820;color:#ddd;border-radius:11px;padding:10px;cursor:pointer}.kd-memory-card footer button:first-child{background:linear-gradient(135deg,#5143aa,#6652c5);color:#fff}.kd-memory-card footer button:last-child{color:#ff8d9b}.kd-memory-card>div:nth-child(2){overflow:auto;padding:14px 16px}.kd-memory-item{display:flex;align-items:flex-start;gap:10px;padding:12px;border:1px solid rgba(255,255,255,.06);background:#15151c;border-radius:13px;margin-bottom:8px;font-size:11px;line-height:1.45}.kd-memory-item span{flex:1}.kd-memory-item button{border:0;background:transparent;color:#777;cursor:pointer;font-size:16px}.kd-memory-empty{text-align:center;color:#777;padding:50px 20px;font-size:11px;line-height:1.7}.kd-memory-empty small{color:#555}`;document.head.appendChild(css);
setInterval(button,800);window.kdOpenMemory=open;window.kdMemoryGet=get;window.kdSaveMemory=add;
})();