(()=>{setTimeout(async()=>{if(!window.supabase)return;const URL='https://qqofizfqkctycyeafgsa.supabase.co',KEY='sb_publishable_MTZuMyuzb0XdtBy3ZGIQZw_pHbXc9xK',sb=window.supabase.createClient(URL,KEY),session=(await sb.auth.getSession()).data.session;if(!session)return;const user=session.user,$=s=>document.querySelector(s);let musicQueue=[],currentIndex=-1,audio=new Audio();audio.preload='metadata';
const style=document.createElement('style');style.textContent='.music-player{margin:8px 0;padding:10px 12px;border:1px solid #ffffff16;background:#ffffff08;border-radius:14px;display:grid;grid-template-columns:38px 1fr;gap:8px;align-items:center}.music-play{width:38px;height:38px;border:0;border-radius:50%;background:#7865ff;color:#fff;cursor:pointer;font-size:16px}.music-info{min-width:0}.music-title{font-size:12px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.music-artist{font-size:10px;opacity:.55;margin-top:2px}.music-progress{width:100%;margin-top:7px;accent-color:#7865ff}.music-times{display:flex;justify-content:space-between;font-size:9px;opacity:.5}.music-controls{display:flex;gap:6px;align-items:center;margin-top:5px}.music-mini{border:0;background:none;color:inherit;cursor:pointer;font-size:12px}.music-upload{display:none}.music-library{padding:10px 12px;border-top:1px solid #ffffff12}.music-add{width:100%;padding:9px;border:1px dashed #ffffff22;background:#ffffff06;color:inherit;border-radius:10px;cursor:pointer}.music-list{margin-top:7px;display:grid;gap:5px}.music-track{display:flex;align-items:center;gap:7px;padding:7px;border-radius:9px;background:#ffffff05}.music-track button{border:0;background:none;color:inherit;cursor:pointer}.music-track-name{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px}';document.head.appendChild(style);
const fileInput=document.createElement('input');fileInput.type='file';fileInput.accept='audio/*,.mp3,.wav,.m4a,.ogg,.aac,.flac';fileInput.multiple=true;fileInput.className='music-upload';document.body.appendChild(fileInput);
const library=document.createElement('div');library.className='music-library';library.innerHTML='<button class="music-add">🎵 Добавить музыку</button><div class="music-list"></div>';document.querySelector('.info-panel')?.appendChild(library);library.querySelector('.music-add').onclick=()=>fileInput.click();
function fmt(s){if(!isFinite(s))return '0:00';return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
function renderLibrary(){library.querySelector('.music-list').innerHTML=musicQueue.map((t,i)=>'<div class="music-track"><button data-i="'+i+'">▶</button><span class="music-track-name">'+String(t.name).replace(/[&<>\"]/g,'')+'</span></div>').join('');library.querySelectorAll('.music-track button').forEach(b=>b.onclick=()=>play(+b.dataset.i))}
function play(i){if(!musicQueue[i])return;currentIndex=i;audio.src=musicQueue[i].url;audio.play().catch(()=>{});renderLibrary()}
function stop(){audio.pause();audio.currentTime=0}
fileInput.onchange=()=>{[...fileInput.files].forEach(f=>{if(!f.type.startsWith('audio/')&&f.size>0)return;musicQueue.push({name:f.name,url:URL.createObjectURL(f),file:f})});fileInput.value='';renderLibrary();if(currentIndex<0&&musicQueue.length)play(0)};
audio.onended=()=>{if(currentIndex+1<musicQueue.length)play(currentIndex+1)};
window.kdMusic={add:(files)=>{[...files].forEach(f=>musicQueue.push({name:f.name,url:URL.createObjectURL(f),file:f}));renderLibrary()},play,stop,next:()=>play((currentIndex+1)%musicQueue.length),prev:()=>play((currentIndex-1+musicQueue.length)%musicQueue.length),getQueue:()=>musicQueue};
window.kdRenderMusicMessage=function(m){const type=m?.attachment_type||'';if(!type.startsWith('audio/'))return null;const wrap=document.createElement('div');wrap.className='music-player';wrap.dataset.musicId=m.id;wrap.innerHTML='<button class="music-play">▶</button><div class="music-info"><div class="music-title"></div><div class="music-artist">Аудио • KD Messenger</div><input class="music-progress" type="range" min="0" max="100" value="0"><div class="music-times"><span>0:00</span><span>0:00</span></div><div class="music-controls"><button class="music-mini prev">⏮</button><button class="music-mini next">⏭</button></div></div>';wrap.querySelector('.music-title').textContent=m.attachment_name||'Музыка';const p=wrap.querySelector('.music-progress'),playBtn=wrap.querySelector('.music-play'),times=wrap.querySelectorAll('.music-times span');let a=new Audio();a.preload='metadata';sb.storage.from('kd-messenger').createSignedUrl(m.attachment_path,3600).then(r=>{if(r.data?.signedUrl){a.src=r.data.signedUrl}});a.onloadedmetadata=()=>{p.max=a.duration;times[1].textContent=fmt(a.duration)};a.ontimeupdate=()=>{p.value=a.currentTime;times[0].textContent=fmt(a.currentTime)};playBtn.onclick=()=>{if(a.paused){a.play();playBtn.textContent='⏸'}else{a.pause();playBtn.textContent='▶'}};a.onended=()=>playBtn.textContent='▶';p.oninput=()=>{a.currentTime=+p.value};wrap.querySelector('.prev').onclick=()=>{a.currentTime=0};wrap.querySelector('.next').onclick=()=>{a.currentTime=a.duration};return wrap};},700)})();