(()=>{setTimeout(async()=>{if(!window.supabase)return;const URL='https://qqofizfqkctycyeafgsa.supabase.co',KEY='sb_publishable_MTZuMyuzb0XdtBy3ZGIQZw_pHbXc9xK',sb=window.supabase.createClient(URL,KEY),session=(await sb.auth.getSession()).data.session;if(!session)return;const user=session.user,$=s=>document.querySelector(s),typing=$('#typing');let presenceChannel=null,typingTimer=null,typingState=false,heartbeat=null;
const style=document.createElement('style');style.textContent='.presence-dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:5px;background:#5f5f6b}.presence-dot.online{background:#5de28c;box-shadow:0 0 8px #5de28c}.typing-text{color:#8b80ff!important}.last-seen{color:#777;font-size:9px}.read-state{opacity:.9}';document.head.appendChild(style);
function setTyping(on){if(!typing)return;typing.hidden=!on;typing.classList.toggle('typing-text',on)}
function formatSeen(v){if(!v)return 'был(а) давно';const d=new Date(v),diff=Date.now()-d.getTime();if(diff<60000)return 'был(а) только что';if(diff<3600000)return 'был(а) '+Math.floor(diff/60000)+' мин назад';return 'был(а) в '+d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}
async function setPresence(){await sb.from('kd_profiles').update({last_seen:new Date().toISOString(),is_online:true}).eq('id',user.id)}
async function stopPresence(){await sb.from('kd_profiles').update({last_seen:new Date().toISOString(),is_online:false}).eq('id',user.id)}
async function readActive(){const cid=window.kdActiveConversation||document.querySelector('.chat.active')?.dataset.id;if(!cid)return;await sb.from('kd_conversation_members').update({last_read_at:new Date().toISOString()}).eq('conversation_id',cid).eq('user_id',user.id)}
function bindTyping(){const input=$('#messageInput');if(!input)return;input.addEventListener('input',()=>{const cid=window.kdActiveConversation||document.querySelector('.chat.active')?.dataset.id;if(!cid||!presenceChannel)return;if(!typingState){typingState=true;presenceChannel.track({user_id:user.id,typing:true})}clearTimeout(typingTimer);typingTimer=setTimeout(()=>{typingState=false;presenceChannel.track({user_id:user.id,typing:false})},1200)});input.addEventListener('focus',readActive)}
async function bindPresence(cid,otherId){if(presenceChannel){await presenceChannel.unsubscribe();presenceChannel=null}presenceChannel=sb.channel('kd-presence-'+cid,{config:{presence:{key:user.id}}});presenceChannel.on('presence',{event:'sync'},()=>{const state=presenceChannel.presenceState();const online=Object.keys(state).some(k=>k!==user.id&&state[k]?.some(x=>x.user_id===otherId));const status=$('#headerStatus');if(status)status.textContent=online?'онлайн':'был(а) недавно';const dot=$('.status-pill');if(dot)dot.style.background=online?'#5de28c':'#5f5f6b'}).on('presence',{event:'join'},()=>{}).on('presence',{event:'leave'},()=>{}).on('presence',{event:'sync'},()=>{const state=presenceChannel.presenceState();const typingUsers=Object.values(state).flat().some(x=>x.user_id!==user.id&&x.typing);setTyping(typingUsers)}).subscribe(async status=>{if(status==='SUBSCRIBED'){await presenceChannel.track({user_id:user.id,typing:false})}})}
async function setup(){await setPresence();heartbeat=setInterval(setPresence,30000);bindTyping();window.addEventListener('pagehide',stopPresence);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setPresence();else stopPresence()});const originalOpen=window.openChat;if(typeof originalOpen==='function'){window.openChat=async function(c){const r=await originalOpen(c);window.kdActiveConversation=c?.id;const members=await sb.from('kd_conversation_members').select('user_id').eq('conversation_id',c.id);const other=(members.data||[]).map(x=>x.user_id).find(x=>x!==user.id);await bindPresence(c.id,other);await readActive();return r}}}
window.kdBindPresence=bindPresence;window.kdReadActive=readActive;setup()},1200)})();